model_list:
  - model_name: gpt-4o
    litellm_params:
      model: "azure/gpt-4o-NHChatGPTPOCv3"
      api_base: os.environ/AZURE_OPENAI_DEFAULT_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_OPENAI_DEFAULT_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: "2025-01-01-preview"
  - model_name: o3-mini
    litellm_params:
      model: "azure/o3-mini-NHChatGPTPOCv3"
      api_base: os.environ/AZURE_OPENAI_DEFAULT_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_OPENAI_DEFAULT_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: "2025-01-01-preview"
  - model_name: gpt-4.1
    litellm_params:
      model: "azure/gpt-4.1-NHChatGPTPOCv3"
      api_base: os.environ/AZURE_OPENAI_DEFAULT_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_OPENAI_DEFAULT_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: "2025-01-01-preview"
